eConverse-Media/thrive-design

- code/thrive-design-stylesheet-new.css
Updates for this to-do: https://3.basecamp.com/3619374/buckets/32507769/card_tables/cards/7064688282
> NH | sponsors updates

- code/thrive-design-lightbox.js
- code/thrive-design-stylesheet-new.css
This accidentally includes the updates for the sponsors as I was having difficulty pushing to a branch, so that pull request should be accepted first. This is a fix for the lightbox code breaking subsequent JS on pages that do not include a gallery.
> Lightbox dev

- code/thrive-design-stylesheet-new.css
Fixes for the issues in this ticket: https://3.basecamp.com/3619374/buckets/32507769/card_tables/cards/7083111640#__recording_7148138301
> NH | hero text and button colours

- code/thrive-design-stylesheet-new.css
Reference Kanban Card: [https://3.basecamp.com/3619374/buckets/32507769/card_tables/cards/6989797444/edit?focus=kanban_card_title](url)
> MD | RM Overflow: hidden; from child cell of activity feed

- code/thrive-design-stylesheet-new.css
Kanban Cards Reference: [https://3.basecamp.com/3619374/buckets/32507769/card_tables/cards/7232430988/edit?focus=kanban_card_title](url)
> Md | adjust flex for feed cards on homepages

- code/thrive-design-stylesheet-new.css
Conference template nav colours are coming in as white, added CSS to make them primary colour
> Super small update to the conference nav tab colours

- code/thrive-design-general.js
- code/thrive-design-stylesheet-new.css
Added JavaScript and CSS to make the hero a full with carousel and added hover states to the carousel arrows
> NEW FEATURE: Hero Banner Option that is a carousel

- code/thrive-design-stylesheet-new.css
Adjusted paragraph size in hero slider from 16px to 18px
> Adjustment: hero slider paragraph size

- code/thrive-design-stylesheet-new.css
https://3.basecamp.com/3619374/buckets/32507769/card_tables/cards/7383995569#__recording_7469760024
Updates are on this branch; currently available on Site X homepage.
> NH | updates to small column member home widgets

- code/thrive-design-stylesheet-new.css
Updated the activity feed styling to more closely match the base Thrive styling, as we had a lot of really awkward padding changes and the like that weren't robust code.
> NH | streamlining the activity feed styling

- code/thrive-design-stylesheet-new.css
This is for this card: https://3.basecamp.com/3619374/buckets/32507769/card_tables/cards/7608465410
> NH | fixing labels on events feed

- code/thrive-design-stylesheet-new.css
This is for this card:
https://3.basecamp.com/3619374/buckets/32507769/card_tables/cards/7602226594
Fix is in this branch.
> NH | fixing bottom border for arrow links

- code/thrive-design-stylesheet-new.css
https://higherlogic.atlassian.net/browse/TD-11
> login button styling - Jira TD-11

- code/thrive-design-stylesheet-new.css
https://higherlogic.atlassian.net/browse/TD-31
> Progress bar color

- code/thrive-design-stylesheet-new.css
https://higherlogic.atlassian.net/browse/TD-10 - remove thin border on cards without white background
https://higherlogic.atlassian.net/browse/TD-16 - set active states of profile nav and pills to primary theme color
> fix for thin border and active states color update

- code/thrive-design-stylesheet-new.css
updated padding to match the other thrive widget items
https://higherlogic.atlassian.net/browse/TD-46
> polls widget heading does not have needed padding

- code/thrive-design-stylesheet-new.css
to allow for links and buttons, standard text links use OG link color
https://higherlogic.atlassian.net/browse/TD-28
> adjusted code for bio pop up models

- code/thrive-design-stylesheet-new.css
Tested here: https://econversetest.connectedcommunity.org/wds-staging/home/memberhome
> Fix uneven Upcoming Events - JIRA TD-39

- code/thrive-design-stylesheet-new.css
Added new class to previous styling on line 1376 to avoid code redundancy.
> Engagement Leaderboard widget's user rows have too much padding: JIRA TD-38

- code/thrive-design-stylesheet-new.css
applied default text color to hl secondary 15% background row color to be more legible
> TD 52 - Separated hl secondary background class text style from standard secondary BG color

- code/thrive-design-stylesheet-new.css
https://higherlogic.atlassian.net/browse/TD-60
> Suggested contacts ignore btn

- code/thrive-design-stylesheet-new.css
https://higherlogic.atlassian.net/browse/TD-8
> Social card list align - TD-8

- code/thrive-design-stylesheet-new.css
https://higherlogic.atlassian.net/browse/TD-71
> Pagination fix - TD-71

- code/thrive-design-stylesheet-new.css
https://higherlogic.atlassian.net/browse/TD-74
Latest Discussion List card can be found on the WDS Staging site's Sticker Sheet: Home Components page as an example: https://econversetest.connectedcommunity.org/wds-staging/home/sticker-sheet-home-components
> Latest Discussion List card border - TD-74

- code/thrive-design-stylesheet-new.css
Updated code from (removed the !important tag): https://github.com/eConverse-Media/thrive-design/pull/67
Off the main branch.
> Dev Dash Outline Update - TD-72

- code/thrive-design-stylesheet-new.css
Updated code from: https://github.com/eConverse-Media/thrive-design/pull/69
Off the main branch.
> Mobile overlay text fix version2 - TD-69

- code/thrive-design-stylesheet-new.css
https://higherlogic.atlassian.net/browse/TD-81
Tested on Staging site here: https://econversetest.connectedcommunity.org/wds-staging/home
> Icon List colors - TD-81

- code/thrive-design-stylesheet-new.css
Recent Blogs List no image icon to match other All Blogs List widgets and Featured Blogs List widgets
https://higherlogic.atlassian.net/browse/TD-82
> Recent Blogs List no image icon - TD-82

- code/thrive-design-bio-modals.js
Screen reading only text for the Bio Modals close button - placed directly in the JS for the bio-modals close button.
https://higherlogic.atlassian.net/browse/TD-85
> Bio Modals Accessibility close modal text - TD-85
